---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ks1
  name: ks1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ks1
    spec:
      containers:
      - image: registry.codinghere.com/smoloney/ks:v1
        name: ks1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources: {}
      imagePullSecrets:
        - name: harbor-registry
status: {}
