---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ks3
  name: ks3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks3
  template:
    metadata:
      labels:
        app: ks3
    spec:
      initContainers:
      - image: alpine/git
        imagePullPolicy: IfNotPresent
        name: ks3-init-repo
        command:  ['sh', '-c', 'git clone --branch=dev https://github.com/stephenmoloney/ks.git /tmp/ks && cp -r /tmp/ks/kubernetes/ks3/app/src/ /ks3/']
        volumeMounts:
        - name: frontend
          mountPath: /ks3/src
      containers:
      - image: registry.codinghere.com/smoloney/ks-frontend:v3
        name: ks3-frontend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: frontend
            mountPath: /app/src
            readOnly: true
        env:
          - name: DANGEROUSLY_DISABLE_HOST_CHECK
            value: "true"
      - image: registry.codinghere.com/smoloney/ks-backend:v3
        name: ks3-backend
        imagePullPolicy: Always
        command: ["python"]
        args: ["-m", "flask", "run"]
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: harbor-registry
      volumes:
      - name: frontend
        emptyDir: {}
