---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ks1.fullname" . }}
  labels:
    app: {{ template "ks1.name" . }}
    chart: {{ template "ks1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "ks1.name" . }}
    release: {{ .Release.Name }}
