---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ks3.fullname" . }}
  labels:
    app: {{ template "ks3.name" . }}
    chart: {{ template "ks3.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ks3.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ks3.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: "{{ .Chart.Name }}-{{ .Values.init.name }}"
        image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
        imagePullPolicy: {{ .Values.init.image.pullPolicy }}
        command:  ['sh', '-c', 'git clone --branch=dev https://github.com/stephenmoloney/ks.git /tmp/ks && cp -r /tmp/ks/kubernetes/ks3/app/src/ /ks3/']
        volumeMounts:
        - name: {{ .Values.init.volume }}
          mountPath: {{ .Values.init.mountPath }}

      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.frontend.name }}"
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.frontend.ingress.path }}
            port: {{ .Values.frontend.service.internalPort }}
            scheme: {{ .Values.common.service.probesScheme }}
{{ include "ks3.livenessProbeSettings" . | indent 10 }}
        readinessProbe:
          httpGet:
            path: {{ .Values.frontend.ingress.path }}
            port: {{ .Values.frontend.service.internalPort }}
            scheme: {{ .Values.common.service.probesScheme }}
{{ include "ks3.readinessProbeSettings" . | indent 10 }}
        volumeMounts:
          - name: {{ .Values.frontend.volume }}
            mountPath: {{ .Values.frontend.mountPath }}
            readOnly: true
        env:
          - name: DANGEROUSLY_DISABLE_HOST_CHECK
            value: "true"

      - name: "{{ .Chart.Name }}-{{ .Values.backend.name }}"
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        args: ["server.py"]
        ports:
        - containerPort: {{ .Values.backend.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.ingress.path }}
            port: {{ .Values.backend.service.internalPort }}
            scheme: {{ .Values.common.service.probesScheme }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.ingress.path }}
            port: {{ .Values.backend.service.internalPort }}
            scheme: {{ .Values.common.service.probesScheme }}

      imagePullSecrets:
        - name: {{ .Values.common.image.pullSecrets }}

      volumes:
      - name: {{ .Values.frontend.volume }}
        emptyDir: {}
